#include<iostream>
using namespace std;
{
int a1;
int a2;
int a3;
int a4;
int a5;
int a6;
int a7;
int a8;
int a9;
int a10;
int a11;
int a12;
int a13;
int a14;
int a15;
int sum;
int multiply;
int subtract;
int result;
int finalresult;
cout<<"enter first number"<<endl;
cin>>a1;
cout<<"enter 2 number"<<endl;
cin>>a2;
cout<<"enter 3 number"<<endl;
cin>>a3;
cout<<"enter 4 number"<<endl;
cin>>a4;
cout<<"enter 5 number"<<endl;
cin>>a5;
cout<<"enter 6 number"<<endl;
cin>>a6;
cout<<"enter 7 number"<<endl;
cin>>a7;
cout<<"enter 8 number"<<endl;
cin>>a8;
cout<<"enter 9 number"<<endl;
cin>>a9;
cout<<"enter 10 number"<<endl;
cin>>a10;
cout<<"enter 11 number"<<endl;
cin>>a11;
cout<<"enter 12 number"<<endl;
cin>>a12;
cout<<"enter 13 number"<<endl;
cin>>a13;
cout<<"enter 14 number"<<endl;
cin>>a14;
cout<<"enter 15 number"<<endl;
cin>>a15;
sum=a1+a2+a3+a4+a5;
multiply=a6*a7*a8*a9*a10;
subtract=a11-a12-a13-a14-15;
finalresult=(sum+multiply)-subtract;
